### ISSUE TITLE
Cant dismiss bulletins on lockscreen.

### ISSUE THREAD

**Issue by gilshahar7** [limneos/libbulletin#1]
Hey, There is a problem when trying to dismiss a bulletin on the lockscreen.
It looks like its dismissing but its not actually, is there a fix for this?
iOS 10.2

**Comment by ca13ra1** [comment]
Same here. I'm using this in one of my tweaks and it doesn't seem to dismiss on lockscreen.

**Comment by gilshahar7** [comment]
Thanks for the update! works as expected :)
